"""empty message

Revision ID: 161194d2227e
Revises: ac7567b4b637
Create Date: 2019-04-05 23:35:56.926752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '161194d2227e'
down_revision = 'ac7567b4b637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asistencias', 'asistio',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('miembros', 'id_familia',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('seguimientos', 'comentarios_seg',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seguimientos', 'comentarios_seg',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('miembros', 'id_familia',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('asistencias', 'asistio',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    # ### end Alembic commands ###
