"""empty message

Revision ID: 2bc07983c15d
Revises: 5e11b5be0a7e
Create Date: 2018-07-09 15:41:14.068912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2bc07983c15d'
down_revision = '5e11b5be0a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miembros_parientes',
    sa.Column('id_miembro_origen', sa.Integer(), nullable=False),
    sa.Column('id_miembro_destino', sa.Integer(), nullable=False),
    sa.Column('id_parentezco', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_miembro_destino'], ['miembros.id'], ),
    sa.ForeignKeyConstraint(['id_miembro_origen'], ['miembros.id'], ),
    sa.ForeignKeyConstraint(['id_parentezco'], ['parentezcos.id'], )
    )
    op.drop_constraint(u'miembros_ibfk_4', 'miembros', type_='foreignkey')
    op.drop_column(u'miembros', 'id_parentezco')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'miembros', sa.Column('id_parentezco', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key(u'miembros_ibfk_4', 'miembros', 'parentezcos', ['id_parentezco'], ['id'])
    op.drop_table('miembros_parientes')
    # ### end Alembic commands ###
