"""empty message

Revision ID: 366d5b294edc
Revises: 17784e0726e9
Create Date: 2019-03-23 19:01:18.810968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366d5b294edc'
down_revision = '17784e0726e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direcciones', sa.Column('piso_nroletra_via', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('direcciones', 'piso_nroletra_via')
    # ### end Alembic commands ###
