"""empty message

Revision ID: 49c599ff032a
Revises: 
Create Date: 2018-07-18 21:24:24.435212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c599ff032a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direcciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_via', sa.String(length=20), nullable=False),
    sa.Column('nombre_via', sa.String(length=100), nullable=False),
    sa.Column('nro_via', sa.String(length=10), nullable=False),
    sa.Column('portalescalotros_via', sa.String(length=20), nullable=True),
    sa.Column('cp_via', sa.String(length=10), nullable=False),
    sa.Column('ciudad_via', sa.String(length=20), nullable=False),
    sa.Column('provincia_via', sa.String(length=20), nullable=False),
    sa.Column('pais_via', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estadosciviles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_estado', sa.String(length=60), nullable=False),
    sa.Column('descripcion_estado', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parentezcos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_parentezco', sa.String(length=60), nullable=False),
    sa.Column('descripcion_parentezco', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiposmiembros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_tipomiembro', sa.String(length=60), nullable=False),
    sa.Column('descripcion_tipomiembro', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('gruposcaseros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_grupo', sa.String(length=60), nullable=False),
    sa.Column('descripcion_grupo', sa.String(length=200), nullable=True),
    sa.Column('id_direccion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_direccion'], ['direcciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion_pariente', sa.String(length=200), nullable=True),
    sa.Column('id_tipopariente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipopariente'], ['parentezcos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('miembros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('dni_doc', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('fecha_nac', sa.DateTime(), nullable=False),
    sa.Column('fecha_inicio_icecha', sa.DateTime(), nullable=True),
    sa.Column('fecha_miembro', sa.DateTime(), nullable=True),
    sa.Column('fecha_bautismo', sa.DateTime(), nullable=True),
    sa.Column('lugar_bautismo', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('id_direccion', sa.Integer(), nullable=False),
    sa.Column('id_estadoscivil', sa.Integer(), nullable=False),
    sa.Column('id_tipomiembro', sa.Integer(), nullable=False),
    sa.Column('id_grupocasero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_direccion'], ['direcciones.id'], ),
    sa.ForeignKeyConstraint(['id_estadoscivil'], ['estadosciviles.id'], ),
    sa.ForeignKeyConstraint(['id_grupocasero'], ['gruposcaseros.id'], ),
    sa.ForeignKeyConstraint(['id_tipomiembro'], ['tiposmiembros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_miembros_apellidos'), 'miembros', ['apellidos'], unique=False)
    op.create_index(op.f('ix_miembros_email'), 'miembros', ['email'], unique=True)
    op.create_index(op.f('ix_miembros_nombres'), 'miembros', ['nombres'], unique=False)
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_culto', sa.DateTime(), nullable=False),
    sa.Column('asistio', sa.Boolean(), nullable=False),
    sa.Column('id_miembro', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_miembro'], ['miembros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asoc_miembros_parientes',
    sa.Column('asoc_id_miembro', sa.Integer(), nullable=True),
    sa.Column('asoc_id_pariente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asoc_id_miembro'], ['miembros.id'], ),
    sa.ForeignKeyConstraint(['asoc_id_pariente'], ['parientes.id'], )
    )
    op.create_table('familias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apellidos_familia', sa.String(length=60), nullable=False),
    sa.Column('descripcion_familia', sa.String(length=200), nullable=True),
    sa.Column('id_direccion', sa.Integer(), nullable=False),
    sa.Column('id_miembro', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_direccion'], ['direcciones.id'], ),
    sa.ForeignKeyConstraint(['id_miembro'], ['miembros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=60), nullable=False),
    sa.Column('descripcion_rol', sa.String(length=200), nullable=True),
    sa.Column('id_miembro', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_miembro'], ['miembros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seguimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_seg', sa.DateTime(), nullable=False),
    sa.Column('comentarios_seg', sa.Boolean(), nullable=False),
    sa.Column('id_miembro', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_miembro'], ['miembros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telefonos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_tel', sa.String(length=20), nullable=False),
    sa.Column('tipo_tel', sa.String(length=20), nullable=False),
    sa.Column('id_miembro', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_miembro'], ['miembros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telefonos')
    op.drop_table('seguimientos')
    op.drop_table('roles')
    op.drop_table('familias')
    op.drop_table('asoc_miembros_parientes')
    op.drop_table('asistencias')
    op.drop_index(op.f('ix_miembros_nombres'), table_name='miembros')
    op.drop_index(op.f('ix_miembros_email'), table_name='miembros')
    op.drop_index(op.f('ix_miembros_apellidos'), table_name='miembros')
    op.drop_table('miembros')
    op.drop_table('parientes')
    op.drop_table('gruposcaseros')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('tiposmiembros')
    op.drop_table('parentezcos')
    op.drop_table('estadosciviles')
    op.drop_table('direcciones')
    # ### end Alembic commands ###
