"""empty message

Revision ID: 7263a24da5fd
Revises: 495b7437d52a
Create Date: 2019-06-06 16:11:22.957093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7263a24da5fd'
down_revision = '495b7437d52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('miembros', 'hoja_firmada',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('reuniones', sa.Column('comentarios_culto', sa.String(length=100), nullable=True))
    op.drop_column('reuniones', 'comentarios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reuniones', sa.Column('comentarios', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('reuniones', 'comentarios_culto')
    op.alter_column('miembros', 'hoja_firmada',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
