"""empty message

Revision ID: 8bdd50873cf6
Revises: 8630b4f04135
Create Date: 2019-03-14 12:31:00.319208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bdd50873cf6'
down_revision = '8630b4f04135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('tipo_rol', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'tipo_rol')
    # ### end Alembic commands ###
