"""empty message

Revision ID: a89753c78061
Revises: 4b7964e9b661
Create Date: 2019-06-12 16:52:17.671965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a89753c78061'
down_revision = '4b7964e9b661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relacion_asistencias',
    sa.Column('id_miembro', sa.Integer(), nullable=False),
    sa.Column('id_reunion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_miembro'], ['miembros.id'], ),
    sa.ForeignKeyConstraint(['id_reunion'], ['reuniones.id'], ),
    sa.PrimaryKeyConstraint('id_miembro', 'id_reunion')
    )
    op.drop_table('asistencias')
    op.alter_column('miembros', 'hoja_firmada',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('miembros', 'hoja_firmada',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.create_table('asistencias',
    sa.Column('id_miembro', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_reunion', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_miembro'], ['miembros.id'], name='asistencias_ibfk_1'),
    sa.ForeignKeyConstraint(['id_reunion'], ['reuniones.id'], name='asistencias_ibfk_2'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('relacion_asistencias')
    # ### end Alembic commands ###
