"""empty message

Revision ID: a8f231ea597e
Revises: 161194d2227e
Create Date: 2019-04-06 00:11:58.744593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8f231ea597e'
down_revision = '161194d2227e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.Column('id_estadoscivil', sa.Integer(), nullable=False),
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seguimientos', 'comentarios_seg',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.drop_constraint(None, 'miembros', type_='foreignkey')
    op.create_index('id_estadoscivil', 'miembros', ['id_estadocivil'], unique=False)
    op.alter_column('miembros', 'id_estadocivil',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('asistencias', 'asistio',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    # ### end Alembic commands ###
