"""empty message

Revision ID: bd1b04ff6d9a
Revises: a89753c78061
Create Date: 2019-10-16 20:18:09.274713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd1b04ff6d9a'
down_revision = 'a89753c78061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('miembros', 'fecha_bautismo',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('miembros', 'fecha_inicio_icecha',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('miembros', 'fecha_miembro',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('miembros', 'fecha_nac',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('miembros', 'hoja_firmada',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('roles', 'tipo_rol',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=1),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'tipo_rol',
               existing_type=sa.String(length=1),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=False)
    op.alter_column('miembros', 'hoja_firmada',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('miembros', 'fecha_nac',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('miembros', 'fecha_miembro',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('miembros', 'fecha_inicio_icecha',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('miembros', 'fecha_bautismo',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
