"""empty message

Revision ID: d8013c6a9f73
Revises: 473f2fd62f9c
Create Date: 2017-10-06 02:40:09.279022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8013c6a9f73'
down_revision = '473f2fd62f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gruposcaseros', sa.Column('direccion_grupo', sa.String(length=200), nullable=False))
    op.alter_column('gruposcaseros', 'descripcion_grupo',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('gruposcaseros', 'nombre_grupo',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gruposcaseros', 'nombre_grupo',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.alter_column('gruposcaseros', 'descripcion_grupo',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.drop_column('gruposcaseros', 'direccion_grupo')
    # ### end Alembic commands ###
